services:
  - type: web
    name: spring-backend
    env: java
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/backend-0.0.1-SNAPSHOT.jar"
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17